spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

task:
  service:
    url: http://localhost:8080/api/tasks/

logging:
  file:
    name: log
  logback:
    rollingpolicy:
      file-name-pattern: app-%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      max-history: 30
      total-size-cap: 10MB

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY:defaultSecretKey}
    expiration-time: 3600000  # 1 hour

Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Credentials: true
