spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: ${SPRING_DATASOURCE_USERNAME:root}  # Uses environment variable or 'root' as default
    password: ${SPRING_DATASOURCE_PASSWORD:root}  # Uses environment variable or 'root' as default
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  cloud:
    config:
      enabled: false  # Disables Spring Cloud Config

  config:
    import: "optional:configserver:http://localhost:8888"  # Tries to connect to config server, but won't fail if unavailable

logging:
  file:
    name: log
  logback:
    rollingpolicy:
      file-name-pattern: app-%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      max-history: 30
      total-size-cap: 10MB

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY:defaultSecretKey}  # Uses environment variable or 'defaultSecretKey' as default
    expiration-time: 3600000  # 1 hour

task:
  service:
    url: http://localhost:8080/api/tasks/

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Content-Type, Authorization
  allow-credentials: true
